name: fluo
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - numpy
  - h5py
  - matplotlib
  - pandas
  - scikit-learn
  - scikit-image
  - tqdm
  - pip:
    - tensorboard